### ISSUE TITLE
AddCustomAttribute throws Newtonsoft.Json.JsonWriterException: Unsupported type error when used to PathString values

### ISSUE THREAD

**Issue by rejish-tl** [newrelic/newrelic-dotnet-agent#1079]
Similar to the issue mentioned in https://github.com/newrelic/newrelic-dotnet-agent/issues/377 for `StringValues`, but it's for [PathString](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.pathstring?view=aspnetcore-6.0) this time.

**Description**
Error is exactly same as described in the issue https://github.com/newrelic/newrelic-dotnet-agent/issues/377 but this time it's for a different type.

**Expected Behavior**
No errors

**Steps to Reproduce**

1. Create a .NET Core 6 application
2. Add [HttpContext.Request.Path](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.path?view=aspnetcore-6.0#microsoft-aspnetcore-http-httprequest-path) value as custom attribute to transaction.
3. This will result in the following error
```
 NewRelic  ERROR: [pid: 0000, tid: 000] Newtonsoft.Json.JsonWriterException: Unsupported type: Microsoft.AspNetCore.Http.PathString. Use the JsonSerializer class to get the object's JSON representation. Path '[2][0][1]'.
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.JsonWriter.WriteValue(Object value)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(Object value)
   at NewRelic.Agent.Core.JsonConverters.JsonSerializerHelpers.WriteCollection(JsonWriter writer, IEnumerable`1 attribValues)
   at NewRelic.Agent.Core.JsonConverters.EventWireModelSerializer.WriteJson(JsonWriter writer, IEventWireModel value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at NewRelic.Agent.Core.DataTransport.ConnectionHandler.SendDataOverWire[T](ICollectorWire wire, String method, Object[] data)
   at NewRelic.Agent.Core.DataTransport.ConnectionHandler.SendDataRequest[T](String method, Object[] data)
   at NewRelic.Agent.Core.DataTransport.ConnectionManager.SendDataRequest[T](String method, Object[] data)
   at NewRelic.Agent.Core.DataTransport.DataTransportService.TrySendDataRequest[T](String method, Object[] data)
```

**Your Environment**
.NET Core 6

**Comment by JcolemanNR** [comment]
Hello @rejish-tl 

Thanks for filing this issue, we'll take a look at resolving this in a future release.
