### ISSUE TITLE
Agent crash with "System.AccessViolationException: Attempted to read or write protected memory"

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1229]
**Description**
We had an integration test failure overnight: https://github.com/newrelic/newrelic-dotnet-agent/runs/8033655567?check_suite_focus=true#step:11:505
The failure was caused by an unhandled exception being thrown from the test application being exercised:
```
====== RemoteApplication: standard error log =====
 Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Diagnostics.Tracing.EventPipePayloadDecoder.DecodePayload(EventMetadata ByRef, System.ReadOnlySpan`1<Byte>)
   at System.Diagnostics.Tracing.EventPipeEventDispatcher.DispatchEventsToEventListeners()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
**Expected Behavior**
```

Searching for this error and stack trace online, I found this issue in the .NET repo: https://github.com/dotnet/runtime/issues/62145, which matches pretty closely in that this test failure happened for the `net6.0` variant of the test in question, and we do have custom event listeners in the agent for getting CLR metrics (memory, threads, etc.)

It appears that this issue will be fixed in .NET 7.0 when it is released: https://github.com/dotnet/runtime/pull/74389  I've commented on that PR and asked if the fix is going to be backported to .NET 6.0.

Unknowns:
1. How likely this is to affect customers using the agent
2. Whether this is specifically related to the integration test case in question (`MySqlConnectorExecuteReaderTestCoreLatest`).  This test was recently refactored (PR #1220) so we should keep an eye on it.  I believe I have seen this error occur intermittently during ad-hoc testing but it's been a few months so I don't remember anything beyond that.
3. If there's anything we can do about it other than hope Microsoft backports the fix to .NET 6.0

**Steps to Reproduce**
I'm unable to reproduce this locally.  The issue in the dotnet/runtime repo says that it is more likely to be reproduced when the app is published as a single file, which we don't do with our integration test applications.  We can experiment with a test app published as a single file and see if it is more reproducible.

**Your Environment**
Our CI environment (so the `windows-2019` GHA runner with .NET 6.0 installed)

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority P4):*
*Suggested T-Shirt size (Unknown):*

**Comment by nr-ahemsath** [comment]
Updates:
1. This crash is 100% reproducible (on my Windows laptop anyway) when running a .NET 6.0 app, published with the `<PublishSingleFile>` option set to true, and with the agent attached.
2. See the discussion in the `dotnet/runtime` PR linked above: Microsoft seems open to backporting the fix to 6.0, but we need to confirm that the 7.0 fix actually fixes our issue.  I tried testing with the latest "nightly" 7.0 RC1 SDK build and it still crashed, but MSFT confirmed that the fix hasn't made it into the latest nightly build yet, so I'll try again next week.
