### ISSUE TITLE
Null reference exception in WriteJsonImpl

### ISSUE THREAD

**Issue by david-garcia-garcia** [newrelic/newrelic-dotnet-agent#2185]
**Description**

APM is not reporting, see this from the logs:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at NewRelic.Agent.Core.JsonConverters.LoadedModuleWireModelCollectionJsonConverter.WriteJsonImpl(JsonWriter jsonWriter, LoadedModuleWireModelCollection value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at NewRelic.Agent.Core.DataTransport.JsonSerializer.Serialize(Object[] parameters)
   at NewRelic.Agent.Core.DataTransport.ConnectionHandler.SendDataOverWire[T](ICollectorWire wire, String method, Object[] data)
   at NewRelic.Agent.Core.DataTransport.ConnectionHandler.SendDataRequest[T](String method, Object[] data)
   at NewRelic.Agent.Core.DataTransport.ConnectionManager.SendDataRequest[T](String method, Object[] data)
   at NewRelic.Agent.Core.DataTransport.DataTransportService.TrySendDataRequest[T](String method, Object[] data)`

This is a log from an IIS hosted APM'ed application.

**Expected Behavior**

There are no errors, and data ir properly sent to NR APM.

**Steps to Reproduce**

Not sure.

**Your Environment**

This is a Windows Server 2022 image running in an AKS cluster. Base image: FROM mcr.microsoft.com/windows/servercore:ltsc2022

**Additional context**

**For Maintainers Only or Hero Triaging this bug**

**Comment by david-garcia-garcia** [comment]
Unfortunately the dump does not include line numbers, but looking at the implementation:

`private static void WriteJsonImpl(JsonWriter jsonWriter, LoadedModuleWireModelCollection value)
        {
            jsonWriter.WriteValue(JarsName);

            jsonWriter.WriteStartArray();

            foreach (var loadedModule in value.LoadedModules)
            {
                // MODULE
                jsonWriter.WriteStartArray();

                jsonWriter.WriteValue(loadedModule.AssemblyName);
                jsonWriter.WriteValue(loadedModule.Version ?? " ");

                // DATA DICTIONARY
                jsonWriter.WriteStartObject();
                foreach (var item in loadedModule.Data)
                {
                    jsonWriter.WritePropertyName(item.Key);
                    jsonWriter.WriteValue(item.Value.ToString());
                }

                jsonWriter.WriteEndObject();

                jsonWriter.WriteEndArray();
            }

            jsonWriter.WriteEndArray();
        }`

The method should probably check for null argument, plus the only pleace i feel could strongly face a NULL reference is "item.Value.ToString()", it should be handled with null propagation.

**Comment by tippmar-nr** [comment]
@david-garcia-garcia Thanks for your bug report and assessment of the likely cause. We'll work on fixing this bug soon.
