### ISSUE TITLE
SQSRequestHandler.ProcessResponse exceptions

### ISSUE THREAD

**Issue by indy-singh** [newrelic/newrelic-dotnet-agent#2811]
**Description**
While grepping through logs for [this issue](https://github.com/newrelic/newrelic-dotnet-agent/issues/2809). I noticed that this exception is very prevalent (well 1660 lines in 8,216,840 log lines).

```csharp
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NewRelic.Providers.Wrapper.AwsSdk.SQSRequestHandler.<>c__DisplayClass2_0.<HandleSQSRequest>g__ProcessResponse|1(Task responseTask)
   at NewRelic.Agent.Extensions.Providers.Wrapper.Delegates.<>c__DisplayClass8_1`1.<OnSuccess>g__EndSegmentWithPossibleException|1()
   at NewRelic.Agent.Extensions.Providers.Wrapper.IAgentWrapperExtensions.HandleExceptions(IAgent agent, Action action)
```

**Expected Behavior**
An exception should not be thrown.

**Steps to Reproduce**
Any app that listens to SQS in the background.

**Your Environment**
Windows Server 2022
dotnet8 
On-prem
Hosted via IIS
NewRelicDotNetAgent_10.30.0_x64.msi (deployed using DSC: ADDLOCAL=NETCoreSupport)
newrelic-infra-amd64.1.57.1.msi (deployed using DSC)

I think the related method is

https://github.com/newrelic/newrelic-dotnet-agent/blob/9673ef1f28a419962a0e50b45b5380fbdaa14528/src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs#L125

**Comment by nrcventura** [comment]
Thank you for submitting this bug and for the analysis that you have already done. I think that you are correct about one of the lines where this error can occur (the other line is for the async version of the method).
