### ISSUE TITLE
Oracle Unbounded Integration Test Fails with (500) Internal Server Error.

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#359]
**Description**
The Oracle unbounded tests always have a single failure, the test "OracleStoredProcedureTests".  It fails with the following:

```
Exception occurred in try number 1 : System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
           at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
           at System.Net.WebClient.DownloadString(Uri address)
           at NewRelic.Agent.UnboundedIntegrationTests.RemoteServiceFixtures.OracleBasicMvcFixture.OracleParameterizedStoredProcedure(String procedureName) in D:\a\newrelic-dotnet-agent\newrelic-dotnet-agent\tests\Agent\IntegrationTests\UnboundedIntegrationTests\RemoteServiceFixtures\OracleBasicMvcFixture.cs:line 72
           at NewRelic.Agent.UnboundedIntegrationTests.Oracle.OracleStoredProcedureTests.<>c__DisplayClass2_0.<.ctor>b__1() in D:\a\newrelic-dotnet-agent\newrelic-dotnet-agent\tests\Agent\IntegrationTests\UnboundedIntegrationTests\Oracle\OracleStoredProcedureTests.cs:line 45
           at NewRelic.Agent.IntegrationTestHelpers.RemoteServiceFixtures.RemoteApplicationFixture.Initialize() in D:\a\newrelic-dotnet-agent\newrelic-dotnet-agent\tests\Agent\IntegrationTests\IntegrationTestHelpers\RemoteServiceFixtures\RemoteApplicationFixture.cs:line 239
```

This example is from: https://github.com/newrelic/newrelic-dotnet-agent/runs/1387255091?check_suite_focus=true#step:9:26

The other oracle tests always pass (ignoring IP/Firewall issues when all tests fail -- different issue).

**Comment by nr-ahemsath** [comment]
A little deeper into the 500 error, discovered by debugging through the test application (`BasicMVCApplication`, `OracleController`, `OracleParameterizedStoredProcedure`):

(For context, "foo" is the name I supplied for the `procedureName` query parameter when calling the `OracleParameterizedStoredProcedure` - so what *should* happen is that a stored procedure is created named `foo` and then that stored procedure is invoked.)

```
Oracle.ManagedDataAccess.Client.OracleException
  HResult=0x80004005
  Message=ORA-06550: line 1, column 7:
PLS-00905: object SYSTEM.FOO is invalid
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
  Source=Oracle Data Provider for .NET, Managed Driver
  StackTrace:
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at BasicMvcApplication.Controllers.OracleController.OracleParameterizedStoredProcedure(String procedureName) in C:\workspace\newrelic-dotnet-agent\tests\Agent\IntegrationTests\UnboundedApplications\BasicMvcApplication\Controllers\OracleController.cs:line 165
   at System.Web.Mvc.ActionMethodDispatcher.<>c__DisplayClass1.<WrapVoidAction>b__0(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

  This exception was originally thrown at this call stack:
    [External Code]
    BasicMvcApplication.Controllers.OracleController.OracleParameterizedStoredProcedure(string) in OracleController.cs
    [External Code]
```

So, it seems like either we created the stored proc incorrectly, or we're invoking it incorrectly.
