### ISSUE TITLE
Unhandled exception causing IIS worker process being terminated

### ISSUE THREAD

**Issue by kelvingo935** [newrelic/newrelic-dotnet-agent#875]
I want to report an unhandled exception because the log file is locked. This exception is causing the IIS worker to be terminated, resulting in our users not being able to access the application. We had mitigated this issue by restarting the IIS webserver to release the lock on the log file, but it would be great if the team could fix the code to handle the exception and not cause an operational impact.

![mRemoteNG_w6Cw2yGLqj](https://user-images.githubusercontent.com/52148045/149335085-7a088229-5d8d-4907-a52e-7b63808540ff.png)

Source: Application Error
```
Faulting application name: w3wp.exe, version: 10.0.17763.1, time stamp: 0xcfdb13d8
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x391c
Faulting application start time: 0x01d806d843b391d3
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: unknown
Report Id: 5fe0c3fd-43c3-44d7-9a5e-2dd983372681
Faulting package full name: 
Faulting package-relative application ID: 
```

Source: .NET Runtime
```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Web.Hosting.UnsafeIISMethods.MgdMapPathDirect(IntPtr, System.String, System.String, IntPtr ByRef, Int32 ByRef)
   at System.Web.Configuration.ProcessHostConfigUtils.MapPathActual(System.String, System.Web.VirtualPath)
   at System.Web.Configuration.ProcessHostMapPath.MapPathCaching(System.String, System.Web.VirtualPath)
   at System.Web.Configuration.ProcessHostMapPath.System.Web.Configuration.IConfigMapPath2.MapPath(System.String, System.Web.VirtualPath)
   at System.Web.Configuration.WebConfigurationHost.IsConfigRecordRequired(System.String)
   at System.Configuration.BaseConfigurationRecord.hlNeedsChildFor(System.String)
   at System.Configuration.Internal.InternalConfigRoot.GetConfigRecord(System.String)
   at System.Configuration.Internal.InternalConfigRoot.GetUniqueConfigRecord(System.String)
   at System.Web.Configuration.HttpConfigurationSystem.GetUniqueConfigRecord(System.String)
   at System.Web.CachedPathData.Init(System.Web.CachedPathData)
   at System.Web.CachedPathData.GetConfigPathData(System.String)
   at System.Web.Configuration.HttpConfigurationSystem.GetApplicationSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at NewRelic.Agent.Core.Configuration.ConfigurationManagerStatic.GetAppSetting(System.String)
   at NewRelic.Agent.Core.Configuration.DefaultConfiguration.get_AgentLicenseKey()
   at NewRelic.Agent.Core.DataTransport.HttpCollectorWire.GetUri(System.String, NewRelic.Agent.Core.DataTransport.ConnectionInfo)
   at NewRelic.Agent.Core.DataTransport.HttpCollectorWire.SendData(System.String, NewRelic.Agent.Core.DataTransport.ConnectionInfo, System.String)
   at NewRelic.Agent.Core.DataTransport.ConnectionHandler.SendDataOverWire[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](NewRelic.Agent.Core.DataTransport.ICollectorWire, System.String, System.Object[])
   at NewRelic.Agent.Core.DataTransport.ConnectionHandler.SendAgentSettings()
   at NewRelic.Agent.Core.DataTransport.ConnectionHandler.Connect()
   at NewRelic.Agent.Core.DataTransport.ConnectionManager.Connect()
   at NewRelic.Agent.Core.Time.Scheduler+<>c__DisplayClass4_0.<ExecuteOnce>b__0()
   at NewRelic.Agent.Core.Utilities.ActionExtensions.CatchAndLog(System.Action)
   at NewRelic.Agent.Core.Time.Scheduler+<>c__DisplayClass8_0.<PrivateCreateExecuteOnceTimer>b__0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

Source: New Relic .NET Agent (the exact file name has been masked out)
```
ERROR: Unable to write the FileLog log to "C:\ProgramData\New Relic\.NET Agent\logs\xxxxxx.log": The process cannot access the file 'C:\ProgramData\New Relic\.NET Agent\logs\xxxxxx.log' because it is being used by another process.
```

**Comment by kelvingo935** [comment]
Hi @nr-ahemsath, we had 2 servers sitting behind the load balancer, and this issue has only happened once on one of them. 

I'm sure it was because the file is locked. I had tried to delete the specific log file but failed because a process was using the file. I can only delete the log file when I stop the IIS service and restart the service. The issue was resolved after the service had started.

The .NET agent version running on the server is 9.0.0.0.

**Comment by vuqtran88** [comment]
@kelvingo935
Thanks for reporting this issue to us. I'm suspecting the issue is from your system might have many different apps/processes that configured to write to the same New Relic agent logs. There are couple ways to avoid this to happen:

1. Disable logging in the newrelic.config `<log level="off"/>`.
2. Configure the agent to write different agent logs for each of your apps.

**Comment by kelvingo935** [comment]
Hi @vuqtran88, there are no other processes are using these New Relic agents logs files, we can delete it after we stop the IIS service. Googling around the exception and I suspect it's caused by the .NET CLR framework, understand nothing can be done on both ends, we will continue monitoring the New Relic agents on our servers.

Regarding the question that the code has already been wrapped by the try-catch block that asked by @nr-ahemsath, I found out that it is because the `System.AccessViolationException` is not able to handle by the try-catch block as mentioned in https://docs.microsoft.com/en-us/dotnet/api/system.accessviolationexception?redirectedfrom=MSDN&view=net-6.0#accessviolationexception-and-trycatch-blocks
