### ISSUE TITLE
9.5.0 agent segfaults on Alpine linux

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#918]
A customer informed us through support that the 9.5.0 agent is segfaulting their apps on Alpine linux.

I did a quick test with the latest dotnet 6.0 sdk docker container image for alpine and am able to reproduce the crash.

```
Core was generated by `dotnet bin/Debug/net6.0/mvctest.dll'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f538c1c2f8c in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.1/libcoreclr.so
[Current thread is 1 (LWP 122)]
(gdb) bt
#0  0x00007f538c1c2f8c in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.1/libcoreclr.so
#1  0x00007f538c1d9a28 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.1/libcoreclr.so
#2  <signal handler called>
#3  0x0000000000096f06 in ?? ()
#4  0x00007f538b1e74f2 in std::__1::__libcpp_snprintf_l(char*, unsigned long, __locale_struct*, char const*, ...) () from /root/newrelic-netcore20-agent/libNewRelicProfiler.so
#5  0x00007f538b1e9ba1 in std::__1::num_put<wchar_t, std::__1::ostreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> > >::do_put(std::__1::ostreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> >, std::__1::ios_base&, wchar_t, unsigned long) const () from /root/newrelic-netcore20-agent/libNewRelicProfiler.so
#6  0x00007f538b1c98e3 in std::__1::basic_ostream<wchar_t, std::__1::char_traits<wchar_t> >::operator<<(unsigned long) () from /root/newrelic-netcore20-agent/libNewRelicProfiler.so
#7  0x00007f538b13f52b in NewRelic::Profiler::Logger::LogStuff<NewRelic::Profiler::Logger::Logger<std::__1::basic_ofstream<wchar_t, std::__1::char_traits<wchar_t> > >, char const (&) [12], unsigned long, char const (&) [38]> (log=..., level=<optimized out>, args=..., args=..., args=...)
    at /profiler/Profiler/../ThreadProfiler/../Logging/Logger.h:148
#8  0x00007f538b13ead9 in NewRelic::Profiler::Configuration::InstrumentationConfiguration::InstrumentationConfiguration (this=0x7f538b9168b8, instrumentationXmls=...) at /profiler/Profiler/../MethodRewriter/../Configuration/InstrumentationConfiguration.h:46
#9  0x00007f538b13e693 in std::__1::__compressed_pair_elem<NewRelic::Profiler::Configuration::InstrumentationConfiguration, 1, false>::__compressed_pair_elem<std::__1::shared_ptr<std::__1::map<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::basic_string<char16_t, std::__1::char_traits
<char16_t>, std::__1::allocator<char16_t> >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const, std::__1::basic_string<char16_t, std::__1::ch
ar_traits<char16_t>, std::__1::allocator<char16_t> > > > > >&, 0ul> (this=0x7f538b9168b8, __args=...) at /usr/include/c++/v1/memory:2103
#10 std::__1::__compressed_pair<std::__1::allocator<NewRelic::Profiler::Configuration::InstrumentationConfiguration>, NewRelic::Profiler::Configuration::InstrumentationConfiguration>::__compressed_pair<std::__1::allocator<NewRelic::Profiler::Configuration::InstrumentationConfiguration>&, std::__1::shared_ptr<std::__1::map<std::__1::basic_string
<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, std::__1::allocator<std::__1::pair<std::__1::basic_str
ing<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > > > > >&> (this=0x7f538b9168b8, __first_args=..., __second_args=..., __pc=...) at /usr/include/c++/v1/memory:2205
#11 std::__1::__shared_ptr_emplace<NewRelic::Profiler::Configuration::InstrumentationConfiguration, std::__1::allocator<NewRelic::Profiler::Configuration::InstrumentationConfiguration> >::__shared_ptr_emplace<std::__1::shared_ptr<std::__1::map<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std
::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > c
onst, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > > > > >&> (this=0x7f538b9168a0, __args=..., __a=...) at /usr/include/c++/v1/memory:3618
#12 std::__1::shared_ptr<NewRelic::Profiler::Configuration::InstrumentationConfiguration>::make_shared<std::__1::shared_ptr<std::__1::map<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::
less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >
> > >&> (__args=...) at /usr/include/c++/v1/memory:4277
#13 0x00007f538b188c06 in std::__1::make_shared<NewRelic::Profiler::Configuration::InstrumentationConfiguration, std::__1::shared_ptr<std::__1::map<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >,
std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char
16_t> > > > > >&> (__args=...) at /usr/include/c++/v1/memory:4656
#14 NewRelic::Profiler::CorProfilerCallbackImpl::InitializeInstrumentationConfig (this=<optimized out>) at /profiler/Profiler/CorProfilerCallbackImpl.h:1097
#15 0x00007f538b1832bc in NewRelic::Profiler::CorProfilerCallbackImpl::Initialize (this=0x7f538bb412a0, pICorProfilerInfoUnk=0x7f538bb454d0) at /profiler/Profiler/CorProfilerCallbackImpl.h:232
```

The only changes between agent versions 9.4.0 and 9.5.0 are:
1. Internal profiler changes and changes to how the profiler is built for Linux, which almost assuredly caused this bug but don't add any functionality for customers
2. Changes to NuGet package metadata to fix an issue with Chocolately packages maintained by a third party, which should be irrelevant to Linux users.

Therefore, there should be zero impact for customers using the agent on Alpine Linux to stay on 9.4.0.

**Comment by nr-ahemsath** [comment]
We've found that the breakage is caused by our changes to the Linux profiler build process, not the code changes to unify the framework and core profiler callbacks.  We will revert to the old build process as it appears to still work just fine.  Hopefully this change will be short-term.

**Comment by nr-ahemsath** [comment]
Created issue #928 as a followup to straighten out the Linux profiler build process for Alpine.
